apiVersion: v1
kind: Service
metadata:
  name: eakp-api
  namespace: eakp
  labels:
    app.kubernetes.io/name: enterprise-ai-platform-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: enterprise-ai-platform-api
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
