apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: eakp
resources:
  - namespace.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - secret.example.yaml
  - api-deployment.yaml
  - api-service.yaml
  - migration-job.yaml
  - hpa.yaml
  - postgres-demo.yaml
images:
  - name: ghcr.io/your-org/enterprise-ai-platform-api
    newName: ghcr.io/your-org/enterprise-ai-platform-api
    newTag: latest
